spring:
  application:
    name: FANTASTIC1-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/CitizenDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9019   


  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379